#!/bin/sh
# preinst script for openquake
#
# see: dh_installdeb(1)

#set -x
set -e

for dir in  /usr/share/pyshared/openquake /usr/share/doc/python-oq /usr/share/pyshared/openquake-0.4.6.egg-info
do
    rm -rf $dir
done
