#!/bin/bash

# ssh oqt rm -rf /var/tmp/pkgs/dists/oneiric/universe/binary-amd64
ssh oqt mkdir -p /var/tmp/pkgs/dists/oneiric/universe/binary-amd64

for f in "$@"
do
    scp $f oqt:/var/tmp/pkgs/dists/oneiric/universe/binary-amd64/
    scp $f oqt:/var/tmp/pkgs/
done

echo "rebuilding local archive .."
ssh oqt "cd /var/tmp/pkgs/dists/oneiric/universe/binary-amd64; dpkg-scanpackages . /dev/null | tee Packages | gzip -c > Packages.gz"

local_archive_in_sources=`ssh oqt cat /etc/apt/sources.list | grep 'file:..*pkgs' | wc -l`

if [ $local_archive_in_sources -lt 1 ]; then
    echo "adding local archive to sources.list .."
    ssh root@oqt 'echo "deb file:///var/tmp/pkgs oneiric universe" >> /etc/apt/sources.list'
else
    echo "sources.list is good to go"
fi

echo "refreshing packages .."
ssh root@oqt apt-get update
